services:
  app:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - ./database:/app/database
      - ./typeorm:/app/typeorm
    environment:
      - NODE_ENV=development
      - PORT=4000
      - DATABASE_PATH=./database/database_orm.sqlite 